name: map_application
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Map
  cupertino_icons: ^1.0.8
  flutter_map: ^8.2.2
  sliding_up_panel: ^2.0.0+1
  flutter_speed_dial: ^7.0.0
  google_fonts: ^6.3.1
  glassmorphism: ^3.0.0
  lottie: ^3.3.2
  flutter_staggered_animations: ^1.1.1
  animated_bottom_navigation_bar: ^1.4.0
  
  # Core & Services
  latlong2: ^0.9.1
  http: ^1.5.0
  geolocator: ^14.0.2
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.1
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.5.3
  
  # Database
  sqflite: ^2.4.2
  path: ^1.9.1

  # State Management & Models
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  freezed_annotation: ^3.1.0
  equatable: ^2.0.5 # Added for value equality in models


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner:
  riverpod_generator:
  json_serializable:
  freezed:

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
